[project]
site_name = "tinyhgvs"
site_description = "Lightweight HGVS parsing library"
site_author = "Simo V. Zhang"
site_url = "https://svm-zhang.github.io/tinyhgvs/"
repo_name = "svm-zhang/tinyhgvs"
repo_url = "https://github.com/svm-zhang/tinyhgvs"
edit_uri = "edit/main/docs"
copyright = """
Copyright &copy; 2026 tinyhgvs author
"""
extra_css = ["stylesheets/extra.css"]
extra_javascript = [
  "https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js",
  "javascripts/tablesort.js"
]
# Section for navigation configuration
nav = [
  {"Home" = "index.md"},
  {"Unsupported Catelog" = "unsupported.md"},
  {"API reference" = [
    { "Parser" = "api/api.md" },
    { "HGVS Models" = [
      { "Overview" = "api/models.md" },
      { "Nucleotide Models" = "api/models-nucleotide.md" },
      { "Protein Models" = "api/models-protein.md" }
    ]},
    { "Errors" = "api/errors.md" }
  ]}
]

# Section for theme configuration
[project.theme]
font = false
language = "en"

features = [
  "announce.dismiss",
  "content.action.edit",
  "content.action.view",
  "content.code.annotate",
  "content.code.copy",
  "content.code.select",
  "content.footnote.tooltips",
  "content.tabs.link",
  "header.autohide",
  "navigation.expand",
  "navigation.path",
  "navigation.sections",
  "navigation.top",
  "navigation.tracking",
  "search.highlight",
  "toc.follow",
  "toc.integrate"
]


[[project.theme.palette]]
media = "(prefers-color-scheme: light)"
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
media = "(prefers-color-scheme: dark)"
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[project.theme.icon]
repo = "fontawesome/brands/github"
edit = "lucide/pencil"
view = "lucide/view"

# Section for markdown extension configuration 
[project.markdown_extensions.admonition]
[project.markdown_extensions.tables]
[project.markdown_extensions.pymdownx.details]
[project.markdown_extensions.pymdownx.superfences]
custom_fences = [
  { name = "mermaid", class = "mermaid", format = "pymdownx.superfences.fence_code_format"}
]
[project.markdown_extensions.pymdownx.highlight]
anchor_linenums = true
line_spans = "__span"
pygments_lang_class = true
[project.markdown_extensions.pymdownx.tabbed]
alternate_style = true
combine_header_slug = true
[project.markdown_extensions.pymdownx.tabbed.slugify]
object = "pymdownx.slugs.slugify"
kwds = { case = "lower" }


# Section for mkdocstring plugin configuration
[project.plugins.mkdocstrings.handlers.python]
paths = ["py-tinyhgvs/python"]

[project.plugins.mkdocstrings.handlers.python.options]
docstring_style = "google"
merge_init_into_class = true
show_source = false
show_docstring_examples = true
show_docstring_type_aliases = true
show_root_toc_entry = false
show_symbol_type_toc = true
show_symbol_type_heading = true
modernize_annotations = true
separate_signature = true
show_signature_annotations = true
show_signature_type_parameters = true
signature_crossrefs = true
type_parameter_headings = true
members_order = "source"

[project.plugins.mkdocstrings.handlers.python.options.docstring_options]
ignore_init_summary = true
