//! This is where we'll define the HGVS grammar rules

WHITESPACE = _{" "}

ac = @{ ASCII_ALPHANUMERIC+ ~ ("_" ~ ASCII_ALPHANUMERIC+)* }
coord_type = @{ "c" | "g" | "m" | "n" | "r" | "p" }
base = @{ ASCII_DIGIT+ }
offset = @{ ASCII_DIGIT+ }
nucleotide = @{ ASCII_ALPHA }
edit_type = @{ "del" | "ins" | "dup" | "delins"}

utr_prefix = @{ "*" | "-" }
intronic_prefix = @{ "+" | "-" }

pos = {
    (utr_prefix ~ offset) |
    (base ~ (intronic_prefix ~ offset)?)
}

range_nuc = { base ~ "_" ~ base }
range = {
  range_nuc ~ (intronic_prefix ~ offset)?
}

sub = { nucleotide ~ ">" ~ nucleotide }
deletion = { edit_type ~ nucleotide*}

// I might want to separate ac+coord_type from the rest
// use coord_type to call parse_protein, parse_rna, parse_dna for instance
// Do I need to set SOI and EOI? Need to check pest doc
hgvsc = {
    ac ~ ":" ~
    coord_type ~ "." ~
    (range | pos ) ~
    (sub | deletion)
}
