"""Public Python API for the tinyhgvs package.

The package exports:

- `parse_hgvs` as the main parsing entry point
- typed dataclasses and enums from `tinyhgvs.models`
- `TinyHGVSError` and related error enums from `tinyhgvs.errors`
"""

from importlib.metadata import PackageNotFoundError, version

from .api import parse_hgvs
from .errors import ParseHgvsErrorKind, TinyHGVSError
from .models import (
    Accession,
    Allele,
    AlleleForm,
    AllelePhase,
    AlleleStateCertainty,
    AlleleVariant,
    AlternativeAlleleForm,
    CodingDnaOutcome,
    CodingDnaUnknown,
    CopiedSequence,
    CoordinateSystem,
    DerivedAlleleForm,
    HgvsVariant,
    KnownLocation,
    KnownProteinFrameshiftStop,
    KnownProteinInsertion,
    KnownQuantity,
    KnownRepeatUnit,
    Location,
    LiteralSequence,
    NucleotideAnchor,
    NucleotideCoordinate,
    NucleotideDeletion,
    NucleotideDeletionInsertion,
    NucleotideDuplication,
    NucleotideEdit,
    NucleotideInsertion,
    NucleotideInversion,
    NucleotideNoChange,
    NucleotideRepeat,
    NucleotideSequenceItem,
    NucleotideSubstitution,
    OmittedProteinFrameshiftStop,
    OutcomeCertainty,
    PossibleRange,
    ProteinCoordinate,
    ProteinDeletion,
    ProteinDeletionInsertion,
    ProteinDuplication,
    ProteinEdit,
    ProteinExtension,
    ProteinExtensionTerminal,
    ProteinFrameshift,
    ProteinFrameshiftStop,
    ProteinInsertion,
    ProteinNoChange,
    ProteinNotProduced,
    ProteinOutcome,
    ProteinProduced,
    ProteinProducedAlternatives,
    ProteinRepeat,
    ProteinSubstitution,
    ProteinUnknown,
    Quantity,
    ReferenceSpec,
    Repeat,
    RepeatUnit,
    RnaIndeterminate,
    RnaNoChange,
    RnaNotProduced,
    RnaOutcome,
    RnaProduced,
    RnaUncertainSplicing,
    RnaUnknown,
    TerminatingProteinInsertion,
    UncertainLocation,
    UncertainQuantity,
    UnknownProteinFrameshiftStop,
    UnknownProteinInsertion,
    UnknownQuantity,
    UnknownRepeatUnit,
)

try:
    __version__ = version("tinyhgvs")
except PackageNotFoundError:
    __version__ = "0+unknown"

__all__ = [
    "Accession",
    "Allele",
    "AlleleForm",
    "AllelePhase",
    "AlleleStateCertainty",
    "AlleleVariant",
    "AlternativeAlleleForm",
    "CodingDnaOutcome",
    "CodingDnaUnknown",
    "CopiedSequence",
    "CoordinateSystem",
    "DerivedAlleleForm",
    "HgvsVariant",
    "KnownLocation",
    "KnownProteinFrameshiftStop",
    "KnownProteinInsertion",
    "KnownQuantity",
    "KnownRepeatUnit",
    "Location",
    "LiteralSequence",
    "NucleotideAnchor",
    "NucleotideCoordinate",
    "NucleotideDeletion",
    "NucleotideDeletionInsertion",
    "NucleotideDuplication",
    "NucleotideEdit",
    "NucleotideInsertion",
    "NucleotideInversion",
    "NucleotideNoChange",
    "NucleotideRepeat",
    "NucleotideSequenceItem",
    "NucleotideSubstitution",
    "OmittedProteinFrameshiftStop",
    "OutcomeCertainty",
    "ProteinCoordinate",
    "ProteinDeletion",
    "ProteinDeletionInsertion",
    "ProteinDuplication",
    "ProteinEdit",
    "ProteinExtension",
    "ProteinExtensionTerminal",
    "ProteinFrameshift",
    "ProteinFrameshiftStop",
    "ParseHgvsErrorKind",
    "PossibleRange",
    "ProteinInsertion",
    "ProteinNoChange",
    "ProteinNotProduced",
    "ProteinOutcome",
    "ProteinProduced",
    "ProteinProducedAlternatives",
    "ProteinRepeat",
    "ProteinSubstitution",
    "ProteinUnknown",
    "Quantity",
    "ReferenceSpec",
    "Repeat",
    "RepeatUnit",
    "RnaIndeterminate",
    "RnaNoChange",
    "RnaNotProduced",
    "RnaOutcome",
    "RnaProduced",
    "RnaUncertainSplicing",
    "RnaUnknown",
    "TerminatingProteinInsertion",
    "TinyHGVSError",
    "UncertainLocation",
    "UncertainQuantity",
    "UnknownProteinFrameshiftStop",
    "UnknownProteinInsertion",
    "UnknownQuantity",
    "UnknownRepeatUnit",
    "__version__",
    "parse_hgvs",
]
